charlist/urls.py
from django.urls import path

from . import views

app_name = "charlist"

urlpatterns = [
    path(
        "session_creator/",
        views.SessionCreator.as_view(),
        name="SessionCreator"
    ),
    path("create_session/", views.add_session, name="AddSession"),
    path(
        "invite/<str:invitation_key>/",
        views.join_session,
        name="JoinSession"
    ),
    path("", views.SessionSelection.as_view(), name="SessionSelector"),
    path(
        "<int:session_id>/char_selector/",
        views.CharSelector.as_view(),
        name="CharSelector"
    ),
    path(
        "<int:session_id>/char_creator/",
        views.CharCreator.as_view(),
        name="CharCreator"),
    path("<int:session_id>/add_char/", views.add_char, name="AddChar"),
    path(
        "<int:session_id>/<int:char_id>/stats/",
        views.CharListStats.as_view(),
        name="CharListStats"
    ),
    path(
        'save_model_form_data/<slug:model_form_name>/',
        views.save_model_form_data,
        name='save_model_form_data'
    ),
    path(
        'save_handwritten_form_data/<str:model_form_name>/',
        views.save_handwritten_form_data,
        name='save_handwritten_form_data'
    ),
    path(
        'save_selected_skills/',
        views.save_selected_skills,
        name='save_selected_skills'
    ),
        path(
        'long_poll/<int:char_id>/',
        views.long_poll,
        name='long_poll'
    ),
]

dnd4e_charlist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("charlist.urls")),
    path("user/", include("charlistAuth.urls")),
    path('admin/', admin.site.urls),
]

charlist/forms.py
from django import forms

from .models import Character, Character_Defenses_Extra, Character_Trained_Skill



class GeneralCharacteristicsForm(forms.ModelForm):

    class Meta:
        model = Character
        exclude = ['session', 'user',]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['deity'].required = False
        self.fields['alignment'].required = False
        self.fields['race'].required = False
        self.fields['char_class'].required = False

    def __str__(self):
        return f"{self.__class__.__name__}"


class DefensesForm(forms.ModelForm):

    class Meta:
        model = Character_Defenses_Extra
        exclude = ['character', 'extra_name',]
    
    def __str__(self):
        return f"{self.__class__.__name__}"
    

class SkillsForm(forms.ModelForm):

    class Meta:
        model = Character_Trained_Skill
        fields = '__all__'
    
    def __str__(self):
        return f"{self.__class__.__name__}"

MODEL_FORM_MAP = {
    'GeneralCharacteristicsForm': GeneralCharacteristicsForm,
    'DefensesForm': DefensesForm,
    'skills': SkillsForm,
}

charlist/views.py
from typing import Any
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db import transaction
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseRedirect,
)
from django.urls import reverse
from django.views import View
from django.views.generic.base import TemplateView
import re

from .constants import (
    ACCESS_ERROR_MESSAGE,
    ALREAD_LOGGED_IN_USER_ERROR,
    DEFENSE_LABELS,
    INVALID_INVITATION_KEY_ERROR_MESSAGE,
    NON_EXISTENT_CHARACTER_ERROR,
    POST_REQUEST_ERROR_MESSAGE,
    USER_VALUE,
    SKILL_DEPENDENCIES,
)
from .forms import GeneralCharacteristicsForm, DefensesForm, MODEL_FORM_MAP
from .models import (
    Ability,
    Character,
    Character_Ability,
    Character_Health,
    Session,
    Session_GM,
    Session_Invitation,
    Session_User,
    Skill,
    Character_Defenses_Extra,
    CharList_Update,
    Character_Trained_Skill
)

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json




# DRY this two ?
# Also they are very dependent on session_id being
def user_is_in_session(user, session: Session | int) -> bool:
    if user.is_anonymous:
        return False
    user_is_gm = Session_GM.objects.filter(Q(gm=user) & Q(session=session)).exists()
    user_is_player = Session_User.objects.filter(
        Q(user=user) & Q(session=session)
    ).exists()
    return user_is_gm | user_is_player

class SessionAccessRequiredMixin(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        session_id = kwargs.get("session_id")
        if not user_is_in_session(request.user, session_id):
            return HttpResponseForbidden(ACCESS_ERROR_MESSAGE)
        return super().dispatch(request, *args, **kwargs)


def session_access_required(function=None):
    def wrapper(request, *args, **kwargs):
        user = request.user
        session = kwargs.get("session_id")
        if not (user_is_in_session(user, session)):
            return HttpResponseForbidden(ACCESS_ERROR_MESSAGE)
        else:
            return function(request, *args, **kwargs)

    return wrapper


class SessionCreator(LoginRequiredMixin, TemplateView):
    template_name = "charlist/SessionCreator.html"


@login_required
def add_session(request: HttpRequest):
    try:
        session_name = request.POST["name"]
    except KeyError:
        return HttpResponse(POST_REQUEST_ERROR_MESSAGE)
    else:
        current_user = request.user
        new_session = Session.objects.create(name=session_name)
        Session_GM.objects.create(session=new_session, gm=current_user)
        Session_Invitation.objects.create(session=new_session)
        return HttpResponseRedirect(reverse("charlist:SessionSelector"))


@login_required
def join_session(request: HttpRequest, invitation_key):
    try:
        session = Session.objects.get(session_invitation__key=invitation_key)
    except Session.DoesNotExist:
        return HttpResponse(INVALID_INVITATION_KEY_ERROR_MESSAGE)
    current_user = request.user

    if user_is_in_session(current_user, session):
        return HttpResponse(ALREAD_LOGGED_IN_USER_ERROR)
    else:
        Session_User.objects.create(session=session, user=current_user)
        return HttpResponseRedirect(
            reverse(
                "charlist:CharSelector",
                kwargs={
                    "session_id": session.id,
                },
            )
        )


class SessionSelection(LoginRequiredMixin, TemplateView):
    template_name = "charlist/SessionSelection.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        cur_user = self.request.user
        context = super().get_context_data(**kwargs)
        sessions = Session.objects.filter(
            Q(session_gm__gm=cur_user) | Q(session_user__user=cur_user)
        ).distinct()    
        session_data = []
        for session in sessions:
            try:
                invitation = Session_Invitation.objects.get(session=session)
            except Session_Invitation.DoesNotExist:
                invitation = Session_Invitation.objects.create(session=session)
            is_gm = Session_GM.objects.filter(session=session,gm=cur_user).exists()
            session_data.append(
                {
                    "info": session,
                    "invite_link": self.request.build_absolute_uri(
                        reverse(
                            "charlist:JoinSession",
                            kwargs={"invitation_key": invitation.key},
                        )
                    ),
                    "is_gm": is_gm,
                }
            )
        context["sessions"] = session_data
        return context


class CharSelector(SessionAccessRequiredMixin, TemplateView):
    template_name = "charlist/CharSelector.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        current_user = self.request.user
        session_id = kwargs['session_id']
        session = get_object_or_404(Session, pk=session_id)

        context = super().get_context_data(**kwargs)
        context["session_id"] = session_id 
        is_gm = Session_GM.objects.filter(session=session, gm=current_user).exists()
        context["is_gm"]=is_gm
        if is_gm:
            context["characters"] = Character.objects.filter(session=session)
        else:
            context["characters"] = Character.objects.filter(
                Q(user=current_user) & Q(session=session)
            )

        return context


class CharCreator(SessionAccessRequiredMixin, TemplateView):
    template_name = "charlist/CharCreator.html"


@session_access_required
def add_char(request, session_id):
    try:
        char_name = request.POST["name"]
    except KeyError:
        return HttpResponse(POST_REQUEST_ERROR_MESSAGE)
    else:
        current_user = request.user
        current_session = Session.objects.get(id=session_id)
        new_character = Character.objects.create(
            session=current_session, user=current_user, name=char_name
        )
        Character_Health.objects.create(character=new_character)
        for ability in Ability.objects.all():
            Character_Ability.objects.create(character=new_character, ability=ability)

        return HttpResponseRedirect(
            reverse(
                "charlist:CharListStats",
                kwargs={"session_id": session_id, "char_id": new_character.id},
            )
        )



class CharListStats(SessionAccessRequiredMixin, TemplateView):
    template_name = "charlist/CharListStats.html"

    def get(self, request, *args, **kwargs):
        session_id = self.kwargs.get("session_id")
        char_id = self.kwargs.get("char_id")
        user = self.request.user
        session = get_object_or_404(Session, pk=session_id)
        user_is_gm_or_player = Session_GM.objects.filter(Q(gm=user) & Q(session=session)).exists() or Character.objects.filter(
            session_id=session_id,
            user_id=user, 
            pk=char_id,
        ).exists()
        if not user_is_gm_or_player:  
            return HttpResponseForbidden(NON_EXISTENT_CHARACTER_ERROR)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        character = Character.objects.get(pk=self.kwargs.get("char_id"))
        context = super().get_context_data(**kwargs)
        context["character_id"] = character.id

        defense_data = Character_Defenses_Extra.objects.filter(character=character)
        context["defenses_form"] = DefensesForm(initial={
            'armor_coefficient': defense_data.first().armor_coefficient if defense_data.exists() else 0,
            'fortitude': defense_data.first().fortitude if defense_data.exists() else 0,
            'reflex': defense_data.first().reflex if defense_data.exists() else 0,
            'will': defense_data.first().will if defense_data.exists() else 0,
        })
        context["character_sheet_form"] = GeneralCharacteristicsForm(
            initial={
                "name": character.name,
                "char_class": character.char_class,
                "race": character.race,
                "xp": character.xp,
                "size": character.size,
                "gender": character.gender,
                "height": character.height,
                "weight": character.weight,
                "alignment": character.alignment,
                "deity": character.deity,
                "speed": character.speed,
                "action_points": character.action_points,
            }
        )

        character_abilities = Character_Ability.objects.filter(character_id=character.id)
        # Преобразуем ключи в строки (имена способностей)
        abilities_data = {
            str(ability.ability): ability.score for ability in character_abilities
        }
        skills = [str(skill) for skill in Skill.objects.all()]
        print(abilities_data)  # Для отладки
        context["abilities_data"] = abilities_data
        context["abilities"] = Ability.objects.values_list("ability", flat=True)

        context["skills"] = skills
        context["senses"] = ["insight", "perception"]
        context["defense_labels"] = DEFENSE_LABELS
        context["user_value"] = USER_VALUE
        context["session_id"] = self.kwargs.get("session_id")
        context["character_name"] = character.name
        context["skill_dependencies"] = SKILL_DEPENDENCIES
        trained_skills = Character_Trained_Skill.objects.filter(character=character).values_list("skill__skill", flat=True)
        context["trained_skills"] = list(trained_skills)

        return context

def create_charlist_update(user,char_id: int):
    updates = CharList_Update.objects.filter(user=user, character_id=char_id)
    if updates.count() > 100:

charlist/templates/charlist/CharCreator.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Сreating a new character
{% endblock %}
{% block content %}
<div class="container text-center my-5">
    <h1 class="mb-4">Сreating a new character</h1>
    <div class="d-flex justify-content-center align-items-center">
        <form action="{% url 'charlist:AddChar' session_id=session_id %}" method="POST" class="form-inline mx-auto w-25">
            {% csrf_token %}
            <fieldset class="form-group mb-3 border border-danger p-4 rounded bg-light shadow">
                <label for="name" class="sr-only">Name</label>
                <input type="text" name="name" id="name" class="form-control" required minlength="2" placeholder="Enter a name">
            </fieldset>
            <button type="submit" class="btn btn-danger">Create</button>
        </form>
    </div>
</div>
{% endblock %}

charlist/templates/charlist/CharListStats.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  Character Sheet
{% endblock %}
{% block content %}
<!-- Forgive me for my sin of putting style in html -->
<div id="saving-indicator" class="bg-danger p-3 rounded shadow text-white position-fixed top-0 start-0 m-3" style="
display: none;
z-index: 9999; 
">Saving...</div>
<div id="char-id" data-char-id="{{ character_id }}" style="display:none;"></div>
<div class="container">
    <div class="row">
        <div class="col-md-5 mb-4">
            <h1 class="text-center" onclick="toggleVisibility('senses')">
                SENSES <span id="icon-senses" class="toggle-icon">▼</span>
            </h1>
            <div id="senses" class="bg-light p-3 rounded shadow" style="display: none;">
                {% include "includes/senses.html" %}
            </div>
        </div>
        <div class="col-md-7 mb-4">
            <h1 class="text-center" onclick="toggleVisibility('defenses')">
                DEFENSES <span id="icon-defenses" class="toggle-icon">▼</span>
            </h1>
            <div id="defenses" class="bg-light p-3 rounded shadow" style="display: none;">
                {% include "includes/defenses.html" %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 mb-4">
            <h1 class="text-center" onclick="toggleVisibility('character')">
                CHARACTER <span id="icon-character" class="toggle-icon">▼</span>
            </h1>
            <div id="character" class="bg-light p-3 rounded shadow" style="display: none;">
                {% include "includes/general_characteristics.html" %}
            </div>

            <h1 class="text-center" onclick="toggleVisibility('abilities')">
                ABILITIES <span id="icon-abilities" class="toggle-icon">▼</span>
            </h1>
            <div id="abilities" class="bg-light p-3 rounded shadow h-50" style="display: none;">
                {% include "includes/abilities.html" %}
            </div>
        </div>

        <div class="col-md-6 mb-3 d-flex flex-column justify-content-between">
            <h1 class="text-center" onclick="toggleVisibility('skills')">
                SKILLS <span id="icon-skills" class="toggle-icon">▼</span>
            </h1>
            <div id="skills" class="bg-light p-3 rounded shadow" style="display: none;">
                {% include "includes/skills.html" %}
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/charlist_scripts.js' %}"></script>
<!-- load in jquery from google's server -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock %}

charlist/templates/charlist/CharSelector.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Character sheets
{% endblock %}
{% block content %}
<div class="container text-center my-5 w-50">

  <h1 class="mb-4">Character Sheets  {%if is_gm%}[gm]{%endif%}</h1>
  <div class="characters_container mb-4 border border-danger p-4 rounded bg-light shadow">
      {% for char in characters %}
      <div class="character my-2">
          <a href="{% url 'charlist:CharListStats' session_id=session_id char_id=char.id %}" class="btn btn-outline-danger w-25">{{ char.name }}</a>
      </div>
      {% endfor %}
  </div>
  <div class="char_add_container">
      <a href="{% url 'charlist:CharCreator' session_id=session_id %}" class="btn btn-danger btn-lg">Create new character</a>
  </div>
</div>
{% endblock %}

charlist/templates/charlist/SessionCreator.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Сreating a new session
{% endblock %}
{% block content %}
<h1 class="mb-4 d-flex justify-content-center">Сreating a new session</h1>
<div class="container d-flex justify-content-center align-items-center">
    <form action="{% url 'charlist:AddSession' %}" method="POST" class="border border-danger p-4 rounded bg-light shadow">
        {% csrf_token %}
        <fieldset class="mb-3">
            <label for="name" class="form-label">Session Name</label>
            <input type="text" name="name" id="name" required minlength="2" class="form-control" placeholder="Enter session name">
        </fieldset>
        <button type="submit" class="btn btn-danger w-100">Create</button>
    </form>
</div>
{% endblock %}

charlist/templates/charlist/SessionSelection.html
{% extends "base.html" %}
{% load static %}
{% block title %}
My sessions
{% endblock %}
{% block content %}
<h1 id="my-session-header" class="mb-4 d-flex justify-content-center">My sessions</h1>
<div class="container mt-5">
  <div class="sessions_container text-center border border-danger p-4 rounded bg-light shadow">
    <div class="row justify-content-center">
      {% for session in sessions %}
      <div class="col-md-8 mb-3">
        <div class="session border border-3 p-3 mb-3 rounded d-flex justify-content-between align-items-center">
          <a href="{% url 'charlist:CharSelector' session_id=session.info.id %}"
            class="text-decoration-none text-danger">
            {{ session.info.name }}
          </a>

          <div class="right-session-side d-flex ">
            {% if session.is_gm %}
            <div class="gm-icon text px-3 border-3" title="Game Master">
              [gm]
            </div>
            {% endif %}
            <button class="btn btn-outline-danger btn-sm" onclick="copyToClipboard(this, '{{ session.invite_link }}')">
              Copy Invite Link
            </button>
          </div>

        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="session_add_container text-center mt-4">
    <button id="create-session-btn-redirect" type="button" class="btn btn-danger">
      <a class="text-decoration-none text-reset" href="{% url 'charlist:SessionCreator' %}">Create new session</a>
    </button>
  </div>
</div>
<script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}