charlist/urls.py
from django.urls import path

from . import views

app_name = "charlist"

urlpatterns = [
    path(
        "session_creator/",
        views.SessionCreator.as_view(),
        name="SessionCreator"
    ),
    path("create_session/", views.add_session, name="AddSession"),
    path(
        "invite/<str:invitation_key>/",
        views.join_session,
        name="JoinSession"
    ),
    path("", views.SessionSelection.as_view(), name="SessionSelector"),
    path(
        "<int:session_id>/char_selector/",
        views.CharSelector.as_view(),
        name="CharSelector"
    ),
    path(
        "<int:session_id>/char_creator/",
        views.CharCreator.as_view(),
        name="CharCreator"),
    path("<int:session_id>/add_char/", views.add_char, name="AddChar"),
    path(
        "<int:session_id>/<int:char_id>/stats/",
        views.CharListStats.as_view(),
        name="CharListStats"
    ),
    path(
        'save_model_form_data/<slug:model_form_name>/',
        views.save_model_form_data,
        name='save_model_form_data'
    ),
    path(
        'save_handwritten_form_data/<str:model_form_name>/',
        views.save_handwritten_form_data,
        name='save_handwritten_form_data'
    ),
    path(
        'save_selected_skills/',
        views.save_selected_skills,
        name='save_selected_skills'
    ),
        path(
        'long_poll/<int:char_id>/',
        views.long_poll,
        name='long_poll'
    ),
]

charlistAuth/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import path, reverse_lazy
from django.contrib.auth import views


app_name = "user"

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='auth/login.html'), name='login'), 
    path(
        'registration/', 
        CreateView.as_view(
            template_name='auth/registration.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('user:login'),
        ),
        name='registration',
    ),
    path('logout/', views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'), 
]

dnd4e_charlist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("charlist.urls")),
    path("user/", include("charlistAuth.urls")),
    path('admin/', admin.site.urls),
]

charlistAuth/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p onclick="handleFooterClick()">© DnD4 Character List</p>    
</footer>

charlistAuth/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: pink">
    <div class="container">
      <a class="navbar-brand" href="{% url 'charlist:SessionSelector' %}">
        <img src="{% static 'img/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        <h1 class="d-inline-block align-top">DnD4 Character List</h1>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-danger btn-lg rounded">
                  <a class="text-decoration-none text-reset" href="{% url 'charlist:SessionCreator' %}">Create session</a>
              </button>
              <button type="button" class="btn btn-outline-danger btn-lg rounded" style="display: inline; margin-left: 10px;">
                  <a class="text-decoration-none text-reset" href="{% url 'charlist:SessionSelector' %}">My sessions</a>
              </button>
              <form action="{% url 'user:logout' %}" method="post" style="display: inline; margin-left: 40px;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-danger btn-lg square-btn">Log Out</button>
              </form>
          </div>        
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-danger"><a class="text-decoration-none text-reset"
                  href="{% url 'user:login' %}">Sign In</a></button>
              <button type="button" class="btn btn-outline-danger"><a class="text-decoration-none text-reset"
                  href="{% url 'user:registration' %}">Sign Up</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>